sonar.projectKey=JeiTy29_cognIA-frontend
sonar.organization=JeiTy29
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,public/**,coverage/**
