import type { ActiveQuestionnaireResponseDTO } from './questionnaires.types';

export const mockActiveQuestionnaire: ActiveQuestionnaireResponseDTO = {
    questionnaire_template: {
        id: 'mock-template',
        name: 'Cuestionario CognIA (Mock)',
        version: '1.0',
        description: 'Cuestionario simulado para pruebas de interfaz.',
        is_active: true
    },
    questions: [
        {
            id: 'q1',
            code: 'ANS-01',
            text: 'Se muestra nervioso o preocupado sin motivo aparente.',
            response_type: 'likert',
            disorder_id: 'ansiedad',
            disorder_ids: null,
            position: 1,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q2',
            code: 'ANS-02',
            text: 'Evita participar en actividades por temor a equivocarse.',
            response_type: 'likert',
            disorder_id: 'ansiedad',
            disorder_ids: null,
            position: 2,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q3',
            code: 'DEP-01',
            text: 'Se ha mostrado triste o desanimado durante varios días.',
            response_type: 'likert',
            disorder_id: 'depresion',
            disorder_ids: null,
            position: 3,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q4',
            code: 'DEP-02',
            text: 'Ha perdido interés por juegos o actividades que antes disfrutaba.',
            response_type: 'likert',
            disorder_id: 'depresion',
            disorder_ids: null,
            position: 4,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q5',
            code: 'TDAH-01',
            text: 'Le cuesta mantener la atención en tareas o juegos.',
            response_type: 'likert',
            disorder_id: 'tdah',
            disorder_ids: null,
            position: 5,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q6',
            code: 'TDAH-02',
            text: 'Se mueve en exceso o le cuesta permanecer sentado.',
            response_type: 'likert',
            disorder_id: 'tdah',
            disorder_ids: null,
            position: 6,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q7',
            code: 'COND-01',
            text: 'Muestra conductas desafiantes o desafía reglas de forma repetida.',
            response_type: 'likert',
            disorder_id: 'conducta',
            disorder_ids: null,
            position: 7,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q8',
            code: 'COND-02',
            text: 'Ha tenido episodios de agresividad hacia otras personas o animales.',
            response_type: 'likert',
            disorder_id: 'conducta',
            disorder_ids: null,
            position: 8,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q9',
            code: 'ELIM-01',
            text: 'Ha presentado episodios de pérdida de control de esfínteres en momentos inapropiados.',
            response_type: 'boolean',
            disorder_id: 'eliminacion',
            disorder_ids: null,
            position: 9,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q10',
            code: 'ELIM-02',
            text: 'Estos episodios ocurren al menos una vez por semana.',
            response_type: 'boolean',
            disorder_id: 'eliminacion',
            disorder_ids: null,
            position: 10,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q11',
            code: 'CTX-01',
            text: '¿Cuántas horas duerme en promedio cada noche?',
            response_type: 'integer',
            disorder_id: null,
            disorder_ids: null,
            position: 11,
            response_min: 4,
            response_max: 12,
            response_step: 1,
            response_options: null
        },
        {
            id: 'q12',
            code: 'CTX-02',
            text: 'En una escala del 1 al 10, ¿cómo calificarías su energía diaria?',
            response_type: 'integer',
            disorder_id: null,
            disorder_ids: null,
            position: 12,
            response_min: 1,
            response_max: 10,
            response_step: 1,
            response_options: null
        },
        {
            id: 'q13',
            code: 'OBS-01',
            text: 'Describe brevemente alguna situación reciente que haya llamado tu atención.',
            response_type: 'text',
            disorder_id: null,
            disorder_ids: null,
            position: 13,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q14',
            code: 'OBS-02',
            text: '¿Hay cambios recientes en su entorno que puedan influir en su comportamiento?',
            response_type: 'text',
            disorder_id: null,
            disorder_ids: null,
            position: 14,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q15',
            code: 'ANS-03',
            text: 'Se muestra irritable o inquieto con frecuencia.',
            response_type: 'likert',
            disorder_id: 'ansiedad',
            disorder_ids: null,
            position: 15,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q16',
            code: 'DEP-03',
            text: 'Se queja de cansancio constante o falta de energía.',
            response_type: 'likert',
            disorder_id: 'depresion',
            disorder_ids: null,
            position: 16,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q17',
            code: 'TDAH-03',
            text: 'Interrumpe con frecuencia cuando otros están hablando.',
            response_type: 'likert',
            disorder_id: 'tdah',
            disorder_ids: null,
            position: 17,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q18',
            code: 'COND-03',
            text: 'Ha tenido conflictos con compañeros o figuras de autoridad.',
            response_type: 'likert',
            disorder_id: 'conducta',
            disorder_ids: null,
            position: 18,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q19',
            code: 'ELIM-03',
            text: 'El niño ha expresado vergüenza o malestar por estos episodios.',
            response_type: 'boolean',
            disorder_id: 'eliminacion',
            disorder_ids: null,
            position: 19,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q20',
            code: 'CTX-03',
            text: '¿Cuántas actividades extracurriculares realiza por semana?',
            response_type: 'integer',
            disorder_id: null,
            disorder_ids: null,
            position: 20,
            response_min: 0,
            response_max: 10,
            response_step: 1,
            response_options: null
        },
        {
            id: 'q21',
            code: 'OBS-03',
            text: 'Describe alguna estrategia que haya funcionado para mejorar su conducta.',
            response_type: 'text',
            disorder_id: null,
            disorder_ids: null,
            position: 21,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q22',
            code: 'ANS-04',
            text: 'Se preocupa excesivamente por la opinión de otros.',
            response_type: 'likert',
            disorder_id: 'ansiedad',
            disorder_ids: null,
            position: 22,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q23',
            code: 'DEP-04',
            text: 'Ha mencionado sentimientos de culpa o inutilidad.',
            response_type: 'likert',
            disorder_id: 'depresion',
            disorder_ids: null,
            position: 23,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q24',
            code: 'TDAH-04',
            text: 'Pierde con facilidad objetos necesarios para tareas o actividades.',
            response_type: 'likert',
            disorder_id: 'tdah',
            disorder_ids: null,
            position: 24,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        },
        {
            id: 'q25',
            code: 'OBS-04',
            text: 'Describe cualquier observación adicional que consideres importante.',
            response_type: 'text',
            disorder_id: null,
            disorder_ids: null,
            position: 25,
            response_min: null,
            response_max: null,
            response_step: null,
            response_options: null
        }
    ]
};
